[package]
name = "ssimulacra2_ffmpeg"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.23.0"
clap = { version = "4.5.23", features = ["cargo"] }
ffmpeg-sidecar = "2.0.5"
ssimulacra2 = "0.5.0"
threadpool = "1.8.1"
